/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Mar 1, 2011, 11:35:55 AM
 */
package dk.itu.frigga.debug.demo.gui;

import dk.itu.frigga.device.Device;
import dk.itu.frigga.device.DeviceCategory;
import dk.itu.frigga.device.manager.DeviceManager;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import org.osgi.framework.BundleContext;
import org.osgi.framework.BundleException;
import org.osgi.framework.ServiceReference;

/**
 *
 * @author phylock
 */
public class MainWindow extends JFrame implements WindowListener {

  private BundleContext context;

  /** Creates new form MainWindow */
  public MainWindow(BundleContext context) {
    this.context = context;
    this.addWindowListener(this);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    lst_devices = new javax.swing.JList();
    btn_refresh = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lst_devices.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(lst_devices);

    btn_refresh.setText("jButton1");
    btn_refresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_refreshActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(btn_refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        .addContainerGap(436, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btn_refresh)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
    lst_devices.removeAll();

    final String strCategory = "SimpleLamp";


    ServiceReference ref = context.getServiceReference(DeviceManager.class.getName());
    if(ref != null)
    {
      DeviceManager manager = (DeviceManager)context.getService(ref);
      DeviceCategory category = manager.getDeviceCategory(strCategory);
      if(category != null)
      {
        Iterable<Device> iter = manager.getDevicesByType(category);
        for

      }
      else
      {
        lst_devices.setListData(new String[]{String.format("No %s devices",strCategory)});
      }

    }
    else
    {
      lst_devices.setListData(new String[]{"No DeviceManager service"});
    }
  }//GEN-LAST:event_btn_refreshActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_refresh;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList lst_devices;
  // End of variables declaration//GEN-END:variables

  public void windowOpened(WindowEvent e) {
  }

  public void windowClosing(WindowEvent e) {
    try {
      context.getBundle().stop();
      context = null;
    } catch (BundleException ex) {
      //TODO: use logger service ref
      ex.printStackTrace();
    }
  }

  public void windowClosed(WindowEvent e) {
  }

  public void windowIconified(WindowEvent e) {
  }

  public void windowDeiconified(WindowEvent e) {
  }

  public void windowActivated(WindowEvent e) {
  }

  public void windowDeactivated(WindowEvent e) {
  }
}
