/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogWindow.java
 *
 * Created on Apr 10, 2011, 4:38:15 PM
 */
package dk.itu.frigga.debug.log.impl;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JScrollBar;
import javax.swing.JTable;
import org.osgi.framework.BundleContext;
import org.osgi.service.log.LogEntry;
import org.osgi.service.log.LogListener;
import org.osgi.service.log.LogService;

/**
 *
 * @author phylock
 */
public class LogWindow extends JFrame implements LogListener {
private BundleContext bc;
  /** Creates new form LogWindow */
  public LogWindow(BundleContext bc) {
    this.bc = bc;
    initComponents();
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    jTable1.setDefaultRenderer(Date.class, new DateCellRenderer());
    jTable1.setRowHeight(32);
    jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
    jTable1.getColumnModel().getColumn(0).setMaxWidth(32);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTable1.setModel(new LogTableModel());
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Log", jPanel1);

    jTable2.setModel(new BundleTableModel(bc));
    jScrollPane2.setViewportView(jTable2);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Bundles", jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public void logged(LogEntry log) {
    JScrollBar sb = jScrollPane1.getVerticalScrollBar();
    boolean toEnd = sb.getValue() == sb.getMaximum();
    Entry entry = new Entry(parseType(log.getLevel()), new Date(log.getTime()), log.getBundle().getSymbolicName(), log.getMessage(), log.getException());
    LogTableModel model = (LogTableModel) jTable1.getModel();
    model.addEntry(entry);
    model.fireTableDataChanged();
    if (toEnd) {
      sb.setValue(sb.getMaximum());
    }
  }

  public void fillLogEnties(LogEntry[] entries) {
    LogTableModel model = (LogTableModel) jTable1.getModel();
    for (LogEntry logentry : entries) {
      Entry entry = new Entry(parseType(logentry.getLevel()), new Date(logentry.getTime()), logentry.getBundle().getSymbolicName(), logentry.getMessage(), logentry.getException());
      model.addEntry(entry);
    }
    model.fireTableDataChanged();
    JScrollBar sb = jScrollPane1.getVerticalScrollBar();
    sb.setValue(sb.getMaximum());

  }

  private Entry.Type parseType(int type) {
    switch (type) {
      case LogService.LOG_DEBUG:
        return Entry.Type.Debug;
      case LogService.LOG_ERROR:
        return Entry.Type.Error;
      case LogService.LOG_INFO:
        return Entry.Type.Info;
      case LogService.LOG_WARNING:
        return Entry.Type.Warning;
      default:
        return Entry.Type.Error;
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTable jTable2;
  // End of variables declaration//GEN-END:variables
}
